// {{PKG_NAME}} — a content-automation DSH plugin (generated by create-dsh-content).
//
// ── Pitfalls this file already guards against ─────────────────────────────
// 1. `@deepseek-ai/dsh-tools` is pinned to the `next`-tag version in
//    package.json — npm's `latest` tag is a STALE 0.0.1-rc.1. Never run a bare
//    `npm i @deepseek-ai/dsh-tools` over it.
// 2. Registration is an EFFECT: `ctx.tools.register()` returns a disposer and
//    auto-attaches it to this plugin's fiber, so unloading unregisters the tool.
// 3. Load order = service dependencies (`inject`), never file order.
// 4. Pure ESM (`"type": "module"`); `@deepseek-ai/cordis` is types-only here
//    (`import type` is erased at compile — the host hands you `ctx` at runtime).
// 5. Content plugins make real network calls. Always wrap HTTP in try/catch and
//    classify errors so the agent can retry or skip per platform.
//
import type { Context } from '@deepseek-ai/cordis'
import { defineTool } from '@deepseek-ai/dsh-tools'
import { publish } from './core/publisher.js'
import { validateAll, type CredentialStore } from './services/credential.js'

// Plugin display name, shown in loader diagnostics.
export const name = '{{PLUGIN_ID}}'

// Wait until the host's tool registry (`ctx.tools`) is ready before running.
export const inject = ['tools', 'config']

export function apply(ctx: Context) {
  // Read credentials from the profile config (BYOK).
  // Bracket access handles plugin ids that contain hyphens (e.g. "build-check"),
  // which would otherwise parse as subtraction. `ctx as any` sidesteps the
  // cordis Context type not statically declaring the injected `config` service.
  const creds: CredentialStore = ((ctx as any).config)?.['{{PLUGIN_ID}}']?.platforms ?? {}
  const validation = validateAll(creds)

  ctx.tools.register(defineTool({
    // The name the model uses to call this tool.
    name: '{{TOOL_NAME}}',
    description: 'Publish content to multiple platforms (Dev.to, Bluesky, Mastodon, GitHub gists). Provide content and target platforms; returns per-platform status and links.',

    // Parameter schema — validated BEFORE execute() runs.
    parameters: {
      content: {
        type: 'string',
        description: 'The content to publish. Markdown is supported for article platforms.',
        required: true,
      },
      title: {
        type: 'string',
        description: 'Title for article-style platforms (Dev.to, GitHub gists).',
      },
      platforms: {
        type: 'string',
        description: 'Comma-separated list of target platforms. Omit to publish to all configured platforms.',
      },
    },

    output: {
      schema: {
        type: 'object',
        properties: {
          results: {
            type: 'array',
            required: true,
            description: 'Per-platform publish results.',
            items: {
              type: 'object',
              properties: {
                platform: { type: 'string', required: true },
                status:   { type: 'string', required: true, description: 'success | skipped | error' },
                url:      { type: 'string' },
                message:  { type: 'string' },
              },
              additionalProperties: false,
            },
          },
          summary: { type: 'string', required: true },
        },
        additionalProperties: false,
      },
      render: (_args, value) => {
        const lines = value.results.map((r: any) =>
          `- **${r.platform}**: ${r.status}${r.url ? ` — ${r.url}` : ''}${r.message ? ` (${r.message})` : ''}`,
        ).join('\n')
        return [
          { type: 'text', text: `${value.summary}\n\n${lines}` },
        ]
      },
    },

    async execute(args) {
      const targetPlatforms = args.platforms
        ? args.platforms.split(',').map((s: string) => s.trim())
        : undefined

      const results = await publish({
        content: args.content,
        title: args.title,
        creds,
        targetPlatforms,
      })

      const successCount = results.filter((r) => r.status === 'success').length
      const total = results.length
      const summary = `Published to ${successCount}/${total} platform(s).`

      return { results, summary }
    },
  }))

  console.log(
    `[{{PLUGIN_ID}}] registered "{{TOOL_NAME}}" — ` +
    `platforms configured=${validation.configured}, disabled=${validation.disabled}`,
  )
}
